language: c
env:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - time
cache:
  directories:
    - $HOME/.opam
before_install:
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlbuild ocamlfind
  - opam install earley earley-ocaml
  - opam install camlzip imagelib sqlite3
  - opam install cryptokit cairo lablgl
  - make configure
  - ./configure
  - make
  - make packages
install:
  - make install
script:
  - echo "OK"
os:
  - linux
notifications:
  email:
    - rodolphe.lepigre@inria.fr
